Repository ITYL-12class-4TEAM/FinMate-SERVER, pull requests merged in 2025-08, with the labels that each got.

#64 refactor: community 유저 예외 처리
  src/main/java/org/scoula/community/comment/controller/CommentApiController.java
  src/main/java/org/scoula/community/comment/service/CommentServiceImpl.java
  src/main/java/org/scoula/community/commentlike/service/CommentLikeServiceImpl.java
  src/main/java/org/scoula/community/post/controller/PostApiController.java
  src/main/java/org/scoula/community/post/service/PostServiceImpl.java
  src/main/java/org/scoula/community/postlike/service/PostLikeServiceImpl.java
  src/main/java/org/scoula/community/scrap/controller/ScrapApiController.java
  src/main/java/org/scoula/community/scrap/service/ScrapServiceImpl.java
  src/main/java/org/scoula/security/config/SecurityConfig.java
Labels: enhancement

#65 feat: 예외처리 추가
  src/main/java/org/scoula/response/ResponseCode.java
Labels: bug

#68 refactor: 권한 수정
  src/main/java/org/scoula/community/comment/service/CommentServiceImpl.java
  src/main/java/org/scoula/community/commentlike/service/CommentLikeServiceImpl.java
  src/main/java/org/scoula/community/post/service/PostServiceImpl.java
  src/main/java/org/scoula/community/postlike/service/PostLikeServiceImpl.java
  src/main/java/org/scoula/community/scrap/service/ScrapServiceImpl.java
  src/main/java/org/scoula/security/config/SecurityConfig.java
Labels: refactor

#70 누락된 WMTI_History 파라미터 추가를 위한 PR
  src/main/java/org/scoula/wmti/controller/WMTIController.java
  src/main/java/org/scoula/wmti/util/WMTIHistoryMapperUtil.java
  src/main/resources/org/scoula/wmti/mapper/SurveyResultMapper.xml
Labels: bug

#80 fix: 인기상품 조회 권한 수정
  src/main/java/org/scoula/security/config/SecurityConfig.java
Labels: enhancement

#82 feat: 상품 목록 조회 GET -> POST /search API 변경 및 ProductSearchRequest 적용
  src/main/java/org/scoula/products/controller/ProductApiController.java
Labels: enhancement, feature

#89 Refactor/wmti frontend link - 프론트엔드 페이지 구성/변경을 위한 백엔드단에서의 추가사항
  src/main/java/org/scoula/preinfo/dto/PreInfoViewDTO.java
  src/main/resources/json/survey/wmti_analysis.json
  src/main/resources/json/survey/wmti_question.json
Labels: refactor

#99 refactor: 스웨거 문서 처리용 수정, 적금 상품 필터링을 위한 값 추가
  src/main/java/org/scoula/products/controller/ProductApiController.java
  src/main/java/org/scoula/products/dto/request/ProductSearchRequest.java
  src/main/java/org/scoula/products/dto/response/CategoryDTO.java
  src/main/java/org/scoula/products/dto/response/ProductDTO.java
  src/main/java/org/scoula/products/dto/response/ProductDetailResponse.java
  src/main/java/org/scoula/products/dto/response/ProductListResponse.java
  src/main/java/org/scoula/products/dto/response/SubcategoryDTO.java
  src/main/java/org/scoula/products/dto/response/deposit/DepositProductDTO.java
  src/main/java/org/scoula/products/mapper/FinancialProductMapper.java
  src/main/java/org/scoula/products/service/impl/ProductCompareServiceImpl.java
  src/main/java/org/scoula/products/service/impl/ProductSearchServiceImpl.java
  src/main/resources/org/scoula/products/mapper/DepositProductMapper.xml
  src/main/resources/org/scoula/products/mapper/FinancialProductMapper.xml
Labels: enhancement

#112 Feature/mypage
  src/main/resources/org/scoula/mypage/favorite/mapper/FavoriteProductMapper.xml
Labels: feature
