Repository ITYL-12class-4TEAM/FinMate-SERVER, pull requests merged in 2025-07, with the labels that each got.

#8 feat: 챗봇 세션 및 메시지 관리 기능 구현
  src/main/java/org/scoula/chatbot/controller/ChatBotApiController.java
  src/main/java/org/scoula/chatbot/session/ChatSession.java
  src/main/java/org/scoula/chatbot/session/ChatSessionManager.java
  src/main/java/org/scoula/chatbot/session/SessionCleanupScheduler.java
  src/main/java/org/scoula/chatgpt/controller/ChatGptController.java
  src/main/java/org/scoula/chatgpt/service/ChatGptService.java
  src/main/java/org/scoula/chatgpt/util/ChatGptUtil.java
  src/main/java/org/scoula/common/config/ServletConfig.java
  src/main/java/org/scoula/response/ResponseCode.java
Labels: feature

#32 feat: 댓글 좋아요 CRUD 구현
  .idea/dataSources/4379bdf2-c9b3-4b9b-b808-fd983fa1bb12.xml
  src/main/java/org/scoula/common/config/RootConfig.java
  src/main/java/org/scoula/common/config/ServletConfig.java
  src/main/java/org/scoula/common/exception/BaseException.java
  src/main/java/org/scoula/common/exception/CommonExceptionAdvice.java
  src/main/java/org/scoula/community/comment/exception/CommentExceptionHandler.java
  src/main/java/org/scoula/community/comment/mapper/CommentMapper.java
  src/main/java/org/scoula/community/commentlike/controller/CommentLikeApiController.java
  src/main/java/org/scoula/community/commentlike/domain/CommentLikeVO.java
  src/main/java/org/scoula/community/commentlike/dto/CommentLikeToggleResponseDTO.java
  src/main/java/org/scoula/community/commentlike/mapper/CommentLikeMapper.java
  src/main/java/org/scoula/community/commentlike/service/CommentLikeService.java
  src/main/java/org/scoula/community/commentlike/service/CommentLikeServiceImpl.java
  src/main/java/org/scoula/response/ApiResponse.java
  src/main/java/org/scoula/response/ResponseCode.java
  src/main/resources/org/scoula/community/comment/mapper/CommentMapper.xml
  src/main/resources/org/scoula/community/commentlike/mapper/CommentLikeMapper.xml
Labels: feature

#40 refactor: 게시판별 게시글 전체 조회 기능 추가, 게시글 파일 첨부 수정, TypeHandler 추가
  src/main/java/org/scoula/common/util/UploadFiles.java
  src/main/java/org/scoula/community/post/controller/PostApiController.java
  src/main/java/org/scoula/community/post/domain/CategoryTag.java
  src/main/java/org/scoula/community/post/domain/PostVO.java
  src/main/java/org/scoula/community/post/dto/PostCreateRequestDTO.java
  src/main/java/org/scoula/community/post/dto/PostDetailsResponseDTO.java
  src/main/java/org/scoula/community/post/dto/PostListResponseDTO.java
  src/main/java/org/scoula/community/post/dto/PostUpdateRequestDTO.java
  src/main/java/org/scoula/community/post/mapper/PostMapper.java
  src/main/java/org/scoula/community/post/service/PostService.java
  src/main/java/org/scoula/community/post/service/PostServiceImpl.java
  src/main/java/org/scoula/response/ResponseCode.java
  src/main/resources/mybatis-config.xml
  src/main/resources/org/scoula/community/post/mapper/PostMapper.xml
Labels: refactor

#44 feat: 내가 쓴 게시글, 댓글, 좋아요 조회 및 예외처리 기능 구현
  src/main/java/org/scoula/community/comment/controller/CommentApiController.java
  src/main/java/org/scoula/community/comment/mapper/CommentMapper.java
  src/main/java/org/scoula/community/comment/service/CommentService.java
  src/main/java/org/scoula/community/comment/service/CommentServiceImpl.java
  src/main/java/org/scoula/community/post/controller/PostApiController.java
  src/main/java/org/scoula/community/post/mapper/PostMapper.java
  src/main/java/org/scoula/community/post/service/PostService.java
  src/main/java/org/scoula/community/post/service/PostServiceImpl.java
  src/main/java/org/scoula/community/postlike/controller/PostLikeApiController.java
  src/main/java/org/scoula/community/postlike/mapper/PostLikeMapper.java
  src/main/java/org/scoula/community/postlike/service/PostLikeService.java
  src/main/java/org/scoula/community/postlike/service/PostLikeServiceImpl.java
  src/main/java/org/scoula/community/scrap/service/ScrapServiceImpl.java
  src/main/java/org/scoula/response/ResponseCode.java
  src/main/resources/org/scoula/community/comment/mapper/CommentMapper.xml
  src/main/resources/org/scoula/community/post/mapper/PostMapper.xml
  src/main/resources/org/scoula/community/postlike/mapper/PostLikeMapper.xml
Labels: feature

#50 refactor: 게시글 및 댓글에 대한 좋아요, 스크랩 여부 반환 로직 리팩토링
  src/main/java/org/scoula/community/comment/dto/CommentResponseDTO.java
  src/main/java/org/scoula/community/comment/mapper/CommentMapper.java
  src/main/java/org/scoula/community/comment/service/CommentServiceImpl.java
  src/main/java/org/scoula/community/commentlike/mapper/CommentLikeMapper.java
  src/main/java/org/scoula/community/post/domain/PostVO.java
  src/main/java/org/scoula/community/post/dto/PostDetailsResponseDTO.java
  src/main/java/org/scoula/community/post/dto/PostListResponseDTO.java
  src/main/java/org/scoula/community/post/service/HotPostSchedulerService.java
  src/main/java/org/scoula/community/post/service/PostServiceImpl.java
  src/main/java/org/scoula/community/postlike/mapper/PostLikeMapper.java
  src/main/java/org/scoula/community/postlike/service/PostLikeServiceImpl.java
  src/main/java/org/scoula/community/scrap/service/ScrapService.java
  src/main/java/org/scoula/community/scrap/service/ScrapServiceImpl.java
  src/main/resources/org/scoula/community/commentlike/mapper/CommentLikeMapper.xml
  src/main/resources/org/scoula/community/post/mapper/PostMapper.xml
  src/main/resources/org/scoula/community/postlike/mapper/PostLikeMapper.xml
  src/main/resources/org/scoula/community/scrap/mapper/ScrapMapper.xml
Labels: refactor

#61 refactor: comment 응답값에 nickname 반환
  src/main/java/org/scoula/community/comment/dto/CommentResponseDTO.java
  src/main/java/org/scoula/community/comment/service/CommentServiceImpl.java
Labels: refactor

#60 Feature/wmti test sheets/wmti_analysis 16종 전부 조회하는 GET 메서드 추가.
  build.gradle
  src/main/java/org/scoula/preinfo/dto/PreInfoViewDTO.java
  src/main/java/org/scoula/wmti/controller/WMTIController.java
  src/main/java/org/scoula/wmti/domain/WMTIAnalysis.java
  src/main/java/org/scoula/wmti/service/WMTIService.java
  src/main/java/org/scoula/wmti/service/WMTIServiceImpl.java
  src/main/resources/json/survey/wmti_question.json
Labels: enhancement
